### ISSUE TITLE
Remove playful language

### ISSUE THREAD

**Issue by tarballs-are-good** [capitaomorte/fiasco#8]
Sorry if I sound like a buzzkill with this issue, but can we remove the playful language (e.g., `Fiasco!`) and just keep it to informative, boring output?

The reason I'm asking is because this is being considered to be used within a professional environment. Nothing is "wrong" or "politically incorrect" with the language, but it just (in the eyes of some) makes it seem less serious.

**Comment by capitaomorte** [comment]
Unfortunately, you are absolutely right. I've merged your commit, but will possibly  bring back the "Fiasco!" via some option.
